[package]
name = "type_erase_exercise"
version = "0.1.0"
authors = ["d_ttang <d_ttang@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
mockall = "0.9.1"
